//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/_Game/Input/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""Default"",
            ""id"": ""03e0c0b5-d7d5-47d4-b700-eda856d73db5"",
            ""actions"": [
                {
                    ""name"": ""Menu"",
                    ""type"": ""Button"",
                    ""id"": ""6f7e8255-0341-43dd-8ecb-1a750af9e879"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Reset"",
                    ""type"": ""Button"",
                    ""id"": ""6c10478a-aa12-4b77-a594-d57ec4a241a8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveCursor"",
                    ""type"": ""Value"",
                    ""id"": ""eb668b05-967a-450d-8db5-8e13c64b7f45"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateCursor"",
                    ""type"": ""Value"",
                    ""id"": ""8778d4ed-b3c8-42fc-a470-1823b79acd0d"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""RotateView"",
                    ""type"": ""Value"",
                    ""id"": ""56e7c84d-61f0-4c33-803f-c7109e9c1aa6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""SwitchTileType"",
                    ""type"": ""Value"",
                    ""id"": ""5529011e-9142-41b8-a336-083c7104a57f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Place"",
                    ""type"": ""Button"",
                    ""id"": ""25963d4d-cad4-49a7-bb45-b1bf16ad0f9e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Remove"",
                    ""type"": ""Button"",
                    ""id"": ""ec62f59f-fec5-43a2-bdc0-962be6b00b80"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ClearBoard"",
                    ""type"": ""Button"",
                    ""id"": ""596fe634-56b2-448e-8498-6be0cd45242e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Play"",
                    ""type"": ""Button"",
                    ""id"": ""4e27be9f-451f-451c-84a6-0b8a369a5df9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NextFrame"",
                    ""type"": ""Button"",
                    ""id"": ""285daca9-a32f-4e28-8132-fc8e570d1f8c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel01"",
                    ""type"": ""Button"",
                    ""id"": ""ab349a38-ab58-47a0-9364-194e6b9f86d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel02"",
                    ""type"": ""Button"",
                    ""id"": ""c5fea43f-6259-4804-bd1e-ca99d15cf622"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel03"",
                    ""type"": ""Button"",
                    ""id"": ""a861f81a-bf3d-403c-b4d9-f061eae8eb1f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel04"",
                    ""type"": ""Button"",
                    ""id"": ""13305cf4-6a07-4adb-ace9-b3f54f4427b3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel05"",
                    ""type"": ""Button"",
                    ""id"": ""bb7e4326-2724-4d90-8d30-7c345410b12b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel06"",
                    ""type"": ""Button"",
                    ""id"": ""0be3d3b4-7549-4226-9eeb-053bd8e325bd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel07"",
                    ""type"": ""Button"",
                    ""id"": ""fd70eede-647f-4557-83c2-0478400546ec"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel08"",
                    ""type"": ""Button"",
                    ""id"": ""4b6afb14-1750-4c26-a310-4c0fef688541"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel09"",
                    ""type"": ""Button"",
                    ""id"": ""1f8eef60-a998-4d92-bd30-5b4e3c6e7419"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadLevel10"",
                    ""type"": ""Button"",
                    ""id"": ""80321060-5b40-472b-870b-6306fd1fe768"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""0a74799d-611a-465e-9ce4-53f9c431ca8b"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Place"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f39069f0-395f-4fa4-b166-ba73d513375e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Remove"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ef31faf2-3cb3-424d-be46-795a3b02671a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Play"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""16ce3c9a-3ca8-4172-a2b0-2d83cf225f56"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NextFrame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0702863a-c53c-47e3-b984-16a26a9ca94e"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel01"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d3f53463-2bb7-4901-a15e-a51c4fa4cf2c"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel02"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a4e73706-535f-4449-b552-d671b79b6478"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel03"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9fd95961-ef8b-470f-adf2-e858acd0e1ef"",
                    ""path"": ""<Keyboard>/h"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Menu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""WASD"",
                    ""id"": ""99dac28a-cb10-41ce-a050-947573a9a7e7"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""9ed1fe74-8cd7-421a-87dc-5c1bf82c3142"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""edb170af-e06e-40f9-acf5-0bc76f4f6764"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""fb681e0d-ea4a-4039-b4a4-07e85c4045fe"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""f266c36a-6002-4ce0-8719-9cce227bbec0"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""230c88d8-9ca9-48ba-9481-579f2a170375"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Reset"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""JL"",
                    ""id"": ""640aa601-f8f1-4f21-b6bd-4ce3b295ae1a"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCursor"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""60aea139-c153-40af-8507-666d503085b9"",
                    ""path"": ""<Keyboard>/j"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""cd9cc64e-3e45-4236-8519-cafdd86ee1d2"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateCursor"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""QE"",
                    ""id"": ""3e6b44fb-cba5-4863-9110-9ede721fa46e"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""c95c1272-b524-4789-bee6-78922d50427a"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""c0d5666d-9e9c-45a0-ba5d-cbea54bff2ac"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""9b1e687b-2297-4764-8f80-8c4050d0f8c4"",
                    ""path"": ""<Keyboard>/backspace"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ClearBoard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ColonQuote"",
                    ""id"": ""c4d102ac-442d-43e9-bac0-d201f8c00f26"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTileType"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""f0e9d43f-bb53-41c9-877e-4165bb796936"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTileType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""835c48b6-d341-4c86-abba-ca88a023a29a"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchTileType"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""5ff592ae-8d47-42ef-b67c-ef5b6ca515f4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel04"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0335109d-0b57-45e4-a0a4-2e092e7f9e98"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel05"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc6fe623-5ada-4d80-a377-c6823a223a0c"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel06"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0216ebd4-c467-4d72-8c1d-1453750cb564"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel07"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""acdafba3-8c2c-4584-9ae4-38c442c2deb6"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel08"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""91a02f27-54a7-43dc-b2ac-6339952f2a32"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel09"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""58cf7100-3d47-4f88-ac16-4b37b9e612c1"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadLevel10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Default
        m_Default = asset.FindActionMap("Default", throwIfNotFound: true);
        m_Default_Menu = m_Default.FindAction("Menu", throwIfNotFound: true);
        m_Default_Reset = m_Default.FindAction("Reset", throwIfNotFound: true);
        m_Default_MoveCursor = m_Default.FindAction("MoveCursor", throwIfNotFound: true);
        m_Default_RotateCursor = m_Default.FindAction("RotateCursor", throwIfNotFound: true);
        m_Default_RotateView = m_Default.FindAction("RotateView", throwIfNotFound: true);
        m_Default_SwitchTileType = m_Default.FindAction("SwitchTileType", throwIfNotFound: true);
        m_Default_Place = m_Default.FindAction("Place", throwIfNotFound: true);
        m_Default_Remove = m_Default.FindAction("Remove", throwIfNotFound: true);
        m_Default_ClearBoard = m_Default.FindAction("ClearBoard", throwIfNotFound: true);
        m_Default_Play = m_Default.FindAction("Play", throwIfNotFound: true);
        m_Default_NextFrame = m_Default.FindAction("NextFrame", throwIfNotFound: true);
        m_Default_LoadLevel01 = m_Default.FindAction("LoadLevel01", throwIfNotFound: true);
        m_Default_LoadLevel02 = m_Default.FindAction("LoadLevel02", throwIfNotFound: true);
        m_Default_LoadLevel03 = m_Default.FindAction("LoadLevel03", throwIfNotFound: true);
        m_Default_LoadLevel04 = m_Default.FindAction("LoadLevel04", throwIfNotFound: true);
        m_Default_LoadLevel05 = m_Default.FindAction("LoadLevel05", throwIfNotFound: true);
        m_Default_LoadLevel06 = m_Default.FindAction("LoadLevel06", throwIfNotFound: true);
        m_Default_LoadLevel07 = m_Default.FindAction("LoadLevel07", throwIfNotFound: true);
        m_Default_LoadLevel08 = m_Default.FindAction("LoadLevel08", throwIfNotFound: true);
        m_Default_LoadLevel09 = m_Default.FindAction("LoadLevel09", throwIfNotFound: true);
        m_Default_LoadLevel10 = m_Default.FindAction("LoadLevel10", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Default
    private readonly InputActionMap m_Default;
    private List<IDefaultActions> m_DefaultActionsCallbackInterfaces = new List<IDefaultActions>();
    private readonly InputAction m_Default_Menu;
    private readonly InputAction m_Default_Reset;
    private readonly InputAction m_Default_MoveCursor;
    private readonly InputAction m_Default_RotateCursor;
    private readonly InputAction m_Default_RotateView;
    private readonly InputAction m_Default_SwitchTileType;
    private readonly InputAction m_Default_Place;
    private readonly InputAction m_Default_Remove;
    private readonly InputAction m_Default_ClearBoard;
    private readonly InputAction m_Default_Play;
    private readonly InputAction m_Default_NextFrame;
    private readonly InputAction m_Default_LoadLevel01;
    private readonly InputAction m_Default_LoadLevel02;
    private readonly InputAction m_Default_LoadLevel03;
    private readonly InputAction m_Default_LoadLevel04;
    private readonly InputAction m_Default_LoadLevel05;
    private readonly InputAction m_Default_LoadLevel06;
    private readonly InputAction m_Default_LoadLevel07;
    private readonly InputAction m_Default_LoadLevel08;
    private readonly InputAction m_Default_LoadLevel09;
    private readonly InputAction m_Default_LoadLevel10;
    public struct DefaultActions
    {
        private @PlayerInput m_Wrapper;
        public DefaultActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Menu => m_Wrapper.m_Default_Menu;
        public InputAction @Reset => m_Wrapper.m_Default_Reset;
        public InputAction @MoveCursor => m_Wrapper.m_Default_MoveCursor;
        public InputAction @RotateCursor => m_Wrapper.m_Default_RotateCursor;
        public InputAction @RotateView => m_Wrapper.m_Default_RotateView;
        public InputAction @SwitchTileType => m_Wrapper.m_Default_SwitchTileType;
        public InputAction @Place => m_Wrapper.m_Default_Place;
        public InputAction @Remove => m_Wrapper.m_Default_Remove;
        public InputAction @ClearBoard => m_Wrapper.m_Default_ClearBoard;
        public InputAction @Play => m_Wrapper.m_Default_Play;
        public InputAction @NextFrame => m_Wrapper.m_Default_NextFrame;
        public InputAction @LoadLevel01 => m_Wrapper.m_Default_LoadLevel01;
        public InputAction @LoadLevel02 => m_Wrapper.m_Default_LoadLevel02;
        public InputAction @LoadLevel03 => m_Wrapper.m_Default_LoadLevel03;
        public InputAction @LoadLevel04 => m_Wrapper.m_Default_LoadLevel04;
        public InputAction @LoadLevel05 => m_Wrapper.m_Default_LoadLevel05;
        public InputAction @LoadLevel06 => m_Wrapper.m_Default_LoadLevel06;
        public InputAction @LoadLevel07 => m_Wrapper.m_Default_LoadLevel07;
        public InputAction @LoadLevel08 => m_Wrapper.m_Default_LoadLevel08;
        public InputAction @LoadLevel09 => m_Wrapper.m_Default_LoadLevel09;
        public InputAction @LoadLevel10 => m_Wrapper.m_Default_LoadLevel10;
        public InputActionMap Get() { return m_Wrapper.m_Default; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DefaultActions set) { return set.Get(); }
        public void AddCallbacks(IDefaultActions instance)
        {
            if (instance == null || m_Wrapper.m_DefaultActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Add(instance);
            @Menu.started += instance.OnMenu;
            @Menu.performed += instance.OnMenu;
            @Menu.canceled += instance.OnMenu;
            @Reset.started += instance.OnReset;
            @Reset.performed += instance.OnReset;
            @Reset.canceled += instance.OnReset;
            @MoveCursor.started += instance.OnMoveCursor;
            @MoveCursor.performed += instance.OnMoveCursor;
            @MoveCursor.canceled += instance.OnMoveCursor;
            @RotateCursor.started += instance.OnRotateCursor;
            @RotateCursor.performed += instance.OnRotateCursor;
            @RotateCursor.canceled += instance.OnRotateCursor;
            @RotateView.started += instance.OnRotateView;
            @RotateView.performed += instance.OnRotateView;
            @RotateView.canceled += instance.OnRotateView;
            @SwitchTileType.started += instance.OnSwitchTileType;
            @SwitchTileType.performed += instance.OnSwitchTileType;
            @SwitchTileType.canceled += instance.OnSwitchTileType;
            @Place.started += instance.OnPlace;
            @Place.performed += instance.OnPlace;
            @Place.canceled += instance.OnPlace;
            @Remove.started += instance.OnRemove;
            @Remove.performed += instance.OnRemove;
            @Remove.canceled += instance.OnRemove;
            @ClearBoard.started += instance.OnClearBoard;
            @ClearBoard.performed += instance.OnClearBoard;
            @ClearBoard.canceled += instance.OnClearBoard;
            @Play.started += instance.OnPlay;
            @Play.performed += instance.OnPlay;
            @Play.canceled += instance.OnPlay;
            @NextFrame.started += instance.OnNextFrame;
            @NextFrame.performed += instance.OnNextFrame;
            @NextFrame.canceled += instance.OnNextFrame;
            @LoadLevel01.started += instance.OnLoadLevel01;
            @LoadLevel01.performed += instance.OnLoadLevel01;
            @LoadLevel01.canceled += instance.OnLoadLevel01;
            @LoadLevel02.started += instance.OnLoadLevel02;
            @LoadLevel02.performed += instance.OnLoadLevel02;
            @LoadLevel02.canceled += instance.OnLoadLevel02;
            @LoadLevel03.started += instance.OnLoadLevel03;
            @LoadLevel03.performed += instance.OnLoadLevel03;
            @LoadLevel03.canceled += instance.OnLoadLevel03;
            @LoadLevel04.started += instance.OnLoadLevel04;
            @LoadLevel04.performed += instance.OnLoadLevel04;
            @LoadLevel04.canceled += instance.OnLoadLevel04;
            @LoadLevel05.started += instance.OnLoadLevel05;
            @LoadLevel05.performed += instance.OnLoadLevel05;
            @LoadLevel05.canceled += instance.OnLoadLevel05;
            @LoadLevel06.started += instance.OnLoadLevel06;
            @LoadLevel06.performed += instance.OnLoadLevel06;
            @LoadLevel06.canceled += instance.OnLoadLevel06;
            @LoadLevel07.started += instance.OnLoadLevel07;
            @LoadLevel07.performed += instance.OnLoadLevel07;
            @LoadLevel07.canceled += instance.OnLoadLevel07;
            @LoadLevel08.started += instance.OnLoadLevel08;
            @LoadLevel08.performed += instance.OnLoadLevel08;
            @LoadLevel08.canceled += instance.OnLoadLevel08;
            @LoadLevel09.started += instance.OnLoadLevel09;
            @LoadLevel09.performed += instance.OnLoadLevel09;
            @LoadLevel09.canceled += instance.OnLoadLevel09;
            @LoadLevel10.started += instance.OnLoadLevel10;
            @LoadLevel10.performed += instance.OnLoadLevel10;
            @LoadLevel10.canceled += instance.OnLoadLevel10;
        }

        private void UnregisterCallbacks(IDefaultActions instance)
        {
            @Menu.started -= instance.OnMenu;
            @Menu.performed -= instance.OnMenu;
            @Menu.canceled -= instance.OnMenu;
            @Reset.started -= instance.OnReset;
            @Reset.performed -= instance.OnReset;
            @Reset.canceled -= instance.OnReset;
            @MoveCursor.started -= instance.OnMoveCursor;
            @MoveCursor.performed -= instance.OnMoveCursor;
            @MoveCursor.canceled -= instance.OnMoveCursor;
            @RotateCursor.started -= instance.OnRotateCursor;
            @RotateCursor.performed -= instance.OnRotateCursor;
            @RotateCursor.canceled -= instance.OnRotateCursor;
            @RotateView.started -= instance.OnRotateView;
            @RotateView.performed -= instance.OnRotateView;
            @RotateView.canceled -= instance.OnRotateView;
            @SwitchTileType.started -= instance.OnSwitchTileType;
            @SwitchTileType.performed -= instance.OnSwitchTileType;
            @SwitchTileType.canceled -= instance.OnSwitchTileType;
            @Place.started -= instance.OnPlace;
            @Place.performed -= instance.OnPlace;
            @Place.canceled -= instance.OnPlace;
            @Remove.started -= instance.OnRemove;
            @Remove.performed -= instance.OnRemove;
            @Remove.canceled -= instance.OnRemove;
            @ClearBoard.started -= instance.OnClearBoard;
            @ClearBoard.performed -= instance.OnClearBoard;
            @ClearBoard.canceled -= instance.OnClearBoard;
            @Play.started -= instance.OnPlay;
            @Play.performed -= instance.OnPlay;
            @Play.canceled -= instance.OnPlay;
            @NextFrame.started -= instance.OnNextFrame;
            @NextFrame.performed -= instance.OnNextFrame;
            @NextFrame.canceled -= instance.OnNextFrame;
            @LoadLevel01.started -= instance.OnLoadLevel01;
            @LoadLevel01.performed -= instance.OnLoadLevel01;
            @LoadLevel01.canceled -= instance.OnLoadLevel01;
            @LoadLevel02.started -= instance.OnLoadLevel02;
            @LoadLevel02.performed -= instance.OnLoadLevel02;
            @LoadLevel02.canceled -= instance.OnLoadLevel02;
            @LoadLevel03.started -= instance.OnLoadLevel03;
            @LoadLevel03.performed -= instance.OnLoadLevel03;
            @LoadLevel03.canceled -= instance.OnLoadLevel03;
            @LoadLevel04.started -= instance.OnLoadLevel04;
            @LoadLevel04.performed -= instance.OnLoadLevel04;
            @LoadLevel04.canceled -= instance.OnLoadLevel04;
            @LoadLevel05.started -= instance.OnLoadLevel05;
            @LoadLevel05.performed -= instance.OnLoadLevel05;
            @LoadLevel05.canceled -= instance.OnLoadLevel05;
            @LoadLevel06.started -= instance.OnLoadLevel06;
            @LoadLevel06.performed -= instance.OnLoadLevel06;
            @LoadLevel06.canceled -= instance.OnLoadLevel06;
            @LoadLevel07.started -= instance.OnLoadLevel07;
            @LoadLevel07.performed -= instance.OnLoadLevel07;
            @LoadLevel07.canceled -= instance.OnLoadLevel07;
            @LoadLevel08.started -= instance.OnLoadLevel08;
            @LoadLevel08.performed -= instance.OnLoadLevel08;
            @LoadLevel08.canceled -= instance.OnLoadLevel08;
            @LoadLevel09.started -= instance.OnLoadLevel09;
            @LoadLevel09.performed -= instance.OnLoadLevel09;
            @LoadLevel09.canceled -= instance.OnLoadLevel09;
            @LoadLevel10.started -= instance.OnLoadLevel10;
            @LoadLevel10.performed -= instance.OnLoadLevel10;
            @LoadLevel10.canceled -= instance.OnLoadLevel10;
        }

        public void RemoveCallbacks(IDefaultActions instance)
        {
            if (m_Wrapper.m_DefaultActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IDefaultActions instance)
        {
            foreach (var item in m_Wrapper.m_DefaultActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_DefaultActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public DefaultActions @Default => new DefaultActions(this);
    public interface IDefaultActions
    {
        void OnMenu(InputAction.CallbackContext context);
        void OnReset(InputAction.CallbackContext context);
        void OnMoveCursor(InputAction.CallbackContext context);
        void OnRotateCursor(InputAction.CallbackContext context);
        void OnRotateView(InputAction.CallbackContext context);
        void OnSwitchTileType(InputAction.CallbackContext context);
        void OnPlace(InputAction.CallbackContext context);
        void OnRemove(InputAction.CallbackContext context);
        void OnClearBoard(InputAction.CallbackContext context);
        void OnPlay(InputAction.CallbackContext context);
        void OnNextFrame(InputAction.CallbackContext context);
        void OnLoadLevel01(InputAction.CallbackContext context);
        void OnLoadLevel02(InputAction.CallbackContext context);
        void OnLoadLevel03(InputAction.CallbackContext context);
        void OnLoadLevel04(InputAction.CallbackContext context);
        void OnLoadLevel05(InputAction.CallbackContext context);
        void OnLoadLevel06(InputAction.CallbackContext context);
        void OnLoadLevel07(InputAction.CallbackContext context);
        void OnLoadLevel08(InputAction.CallbackContext context);
        void OnLoadLevel09(InputAction.CallbackContext context);
        void OnLoadLevel10(InputAction.CallbackContext context);
    }
}
